# Mellanox HW Management

MLNX_HW_MANAGEMENT_VERSION = onl.deb9.13.12.2017

MLNX_HW_MANAGEMENT = hw-management_1.mlnx.$(MLNX_HW_MANAGEMENT_VERSION)_amd64.deb
$(MLNX_HW_MANAGEMENT)_SRC_PATH = $(PLATFORM_PATH)/hw-management
SONIC_DPKG_DEBS += $(MLNX_HW_MANAGEMENT)
